---
name: Calling BOTs
on:
  push:
    tags:
      - '*'
jobs:
  Bots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ðŸ“¦ Get version from package.json
        run: |
          version=$(cat ./package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[", ]//g')
          echo "CURRENT_VERSION=$version" >> $GITHUB_ENV

      - name: ðŸ”Ž Check output version
        run: |
          echo "->${{env.CURRENT_VERSION}}<-"

      - name: ðŸ–¥ï¸ Update App
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.READMEBOT_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/laradumps/app/actions/workflows/readmebot.yml/dispatches \
          -d '{"ref":"main","inputs":{"version":"${{env.CURRENT_VERSION}}"}}'

      - name: ðŸ›» Update Laravel Package
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.READMEBOT_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/laradumps/laradumps/actions/workflows/readmebot.yml/dispatches \
          -d '{"ref":"main","inputs":{"version":"${{env.CURRENT_VERSION}}"}}' 

      - name: ðŸ“š Update Docs
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.READMEBOT_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/laradumps/laradumps-docs/actions/workflows/readmebot.yml/dispatches \
          -d '{"ref":"main","inputs":{"version":"${{env.CURRENT_VERSION}}"}}' 
